import type { Vehicle, Service, Area } from "@/types";
import manifest from "../../public/images/image-manifest.json";

const imageManifest = manifest as Record<string, { interior: string[]; exterior: string[] }>;

function getVehicleImages(slug: string): string[] {
  const entry = imageManifest[slug];
  if (!entry) return ["/images/hero/hero-partybus.jpg"];
  return [...entry.interior, ...entry.exterior].slice(0, 20);
}

// ===== PARTY BUSES =====
export const partyBuses: Vehicle[] = [
  { slug: "diamond", name: "Diamond", type: "party-bus", passengers: 30, tagline: "Brilliance in motion", description: "The Diamond party bus shines with its luxurious interior and state-of-the-art entertainment system. Perfect for groups up to 30 passengers looking for an unforgettable experience.", features: ["LED Lighting", "Premium Sound System", "Laser Lights", "Dancing Poles", "Bar Area", "Leather Seating", "Flat Screen TVs", "Climate Control"], images: getVehicleImages("diamond") },
  { slug: "tiffany-miami", name: "Tiffany / Miami", type: "party-bus", passengers: 34, tagline: "South Beach vibes on wheels", description: "Experience the glamour of South Beach with our Tiffany Miami party bus. Featuring a stunning interior designed to make every ride feel like a VIP event.", features: ["LED Lighting", "Premium Sound System", "Dancing Poles", "Bar Area", "Leather Seating", "Flat Screen TVs", "Laser Lights", "Fog Machine"], images: getVehicleImages("tiffany-miami") },
  { slug: "vision-venice", name: "Vision / Venice", type: "party-bus", passengers: 30, tagline: "Where elegance meets energy", description: "The Vision Venice combines sophisticated design with party-ready features. A perfect balance of class and fun for your next event.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Climate Control", "Fiber Optic Ceiling"], images: getVehicleImages("vision-venice") },
  { slug: "gatsby", name: "Gatsby", type: "party-bus", passengers: 38, tagline: "Roaring twenties luxury", description: "Inspired by the opulence of the 1920s, the Gatsby bus brings old-world glamour to modern celebrations. One of our largest buses accommodating up to 38 guests.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "VIP Section", "Champagne Service"], images: getVehicleImages("gatsby") },
  { slug: "hawaii", name: "Hawaii", type: "party-bus", passengers: 34, tagline: "Tropical paradise on the move", description: "Bring the island vibes wherever you go with our Hawaii party bus. Tropical-inspired décor and premium amenities create an unforgettable atmosphere.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Climate Control", "Tropical Décor"], images: getVehicleImages("hawaii") },
  { slug: "mercedes-sprinter", name: "Mercedes Sprinter", type: "party-bus", passengers: 16, tagline: "Compact luxury redefined", description: "The Mercedes Sprinter offers intimate luxury for smaller groups. Perfect for corporate events, airport transfers, and upscale nights out.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TV", "Climate Control", "USB Charging", "Privacy Partition"], images: getVehicleImages("mercedes-sprinter") },
  { slug: "enclave", name: "Enclave", type: "party-bus", passengers: 34, tagline: "Your private sanctuary", description: "Step into the Enclave and leave the ordinary behind. This stunning party bus creates an exclusive atmosphere for up to 34 guests.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Laser Lights", "Climate Control"], images: getVehicleImages("enclave") },
  { slug: "encore", name: "Encore", type: "party-bus", passengers: 34, tagline: "Deserving of an encore", description: "The Encore delivers a performance worthy of its name. With premium features and stunning design, every ride is a standing ovation.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Fog Machine", "Climate Control"], images: getVehicleImages("encore") },
  { slug: "epic", name: "Epic", type: "party-bus", passengers: 40, tagline: "Epic nights start here", description: "Our largest party bus, the Epic accommodates up to 40 passengers. Perfect for the biggest celebrations and events that demand the ultimate experience.", features: ["LED Lighting", "Premium Sound System", "Multiple Bar Areas", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "VIP Lounge", "Laser Show"], images: getVehicleImages("epic") },
  { slug: "escape", name: "Escape", type: "party-bus", passengers: 38, tagline: "Your ultimate getaway", description: "Escape the ordinary with this stunning 38-passenger party bus. Designed for those who want to make every moment count.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Climate Control", "Privacy Windows"], images: getVehicleImages("escape") },
  { slug: "exhibit", name: "Exhibit", type: "party-bus", passengers: 36, tagline: "A masterpiece on wheels", description: "The Exhibit is a showcase of luxury and entertainment. Every detail has been crafted to create an extraordinary experience for up to 36 guests.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Art-Inspired Interior", "Climate Control"], images: getVehicleImages("exhibit") },
  { slug: "fantasy", name: "Fantasy", type: "party-bus", passengers: 34, tagline: "Where dreams ride", description: "Turn your fantasies into reality aboard this stunning party bus. Dreamlike ambiance and premium amenities make every journey magical.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Fiber Optic Ceiling", "Climate Control"], images: getVehicleImages("fantasy") },
  { slug: "fashion-versace", name: "Fashion / Versace", type: "party-bus", passengers: 34, tagline: "Haute couture on wheels", description: "Fashion meets function in our Versace-inspired party bus. Bold design elements and luxury finishes create a runway-worthy experience.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Designer Leather Seating", "Flat Screen TVs", "Dancing Poles", "Fashion-Forward Interior", "Climate Control"], images: getVehicleImages("fashion-versace") },
  { slug: "krystal", name: "Krystal", type: "party-bus", passengers: 36, tagline: "Crystal clear luxury", description: "The Krystal party bus sparkles with its premium crystal-inspired décor and top-of-the-line entertainment features for up to 36 passengers.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Crystal Accents", "Climate Control"], images: getVehicleImages("krystal") },
  { slug: "olympus", name: "Olympus", type: "party-bus", passengers: 30, tagline: "Rise to greatness", description: "Named after the home of the gods, the Olympus delivers a truly divine experience. Premium luxury for up to 30 distinguished guests.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Grecian-Inspired Design", "Climate Control"], images: getVehicleImages("olympus") },
  { slug: "vip", name: "VIP", type: "party-bus", passengers: 50, tagline: "The ultimate VIP experience", description: "Our flagship VIP party bus accommodates up to 50 passengers, making it the largest and most luxurious option in our fleet.", features: ["LED Lighting", "Premium Sound System", "Multiple Bar Areas", "Leather Seating", "Multiple Flat Screen TVs", "Dancing Poles", "VIP Sections", "Full Laser Show"], images: getVehicleImages("vip") },
  { slug: "martini", name: "Martini", type: "party-bus", passengers: 16, tagline: "Shaken, not stirred", description: "The Martini offers an intimate, sophisticated atmosphere inspired by classic cocktail culture. Perfect for smaller upscale gatherings.", features: ["LED Lighting", "Premium Sound System", "Cocktail Bar", "Leather Seating", "Flat Screen TV", "Climate Control", "Martini-Themed Interior", "USB Charging"], images: getVehicleImages("martini") },
  { slug: "mercedes-charter", name: "Mercedes Charter", type: "party-bus", passengers: 14, tagline: "Executive class travel", description: "The Mercedes Charter provides executive-level transportation for smaller groups. Ideal for corporate events and VIP transportation.", features: ["LED Lighting", "Premium Sound System", "Mini Bar", "Leather Captain Chairs", "Flat Screen TV", "Climate Control", "USB Charging", "Privacy Glass"], images: getVehicleImages("mercedes-charter") },
  // Missing from new design - added from old site
  { slug: "white-pearl", name: "White Pearl", type: "party-bus", passengers: 34, tagline: "Pure elegance on wheels", description: "The White Pearl party bus radiates sophistication with its pristine white exterior and luxurious interior. A stunning choice for weddings and upscale events.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Pearl White Interior", "Climate Control"], images: getVehicleImages("white-pearl") },
  { slug: "lounge", name: "Lounge", type: "party-bus", passengers: 30, tagline: "Relax in luxury", description: "The Lounge edition offers a relaxed yet luxurious atmosphere. Designed for those who want to enjoy the ride as much as the destination.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Plush Seating", "Flat Screen TVs", "Lounge Layout", "Fiber Optic Ceiling", "Climate Control"], images: getVehicleImages("lounge") },
  { slug: "chicago-edition", name: "Chicago Edition", type: "party-bus", passengers: 36, tagline: "Chicago pride on wheels", description: "Our signature Chicago Edition party bus celebrates the spirit of the Windy City. Custom Chicago-themed interior with all the premium amenities.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "Chicago-Themed Design", "Climate Control"], images: getVehicleImages("chicago-edition") },
];

// ===== LIMOUSINES =====
export const limousines: Vehicle[] = [
  { slug: "cadillac-escalade", name: "Cadillac Escalade", type: "limo", passengers: 20, tagline: "American luxury at its finest", description: "The Cadillac Escalade limousine represents the pinnacle of American luxury. With room for up to 20 passengers, it combines iconic styling with premium amenities.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Fiber Optic Ceiling", "Climate Control", "Privacy Partition"], images: getVehicleImages("cadillac-escalade") },
  { slug: "hummer-h2-white-pearl", name: "Hummer H2 White Pearl", type: "limo", passengers: 25, tagline: "Bold, beautiful, breathtaking", description: "Our White Pearl Hummer H2 limousine is an absolute head-turner. With its stunning exterior and luxurious interior, it makes a statement at any event.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Pole", "Laser Lights", "Climate Control"], images: getVehicleImages("hummer-h2-white-pearl") },
  { slug: "hummer-h2-double-axle", name: "Hummer H2 Double Axle", type: "limo", passengers: 25, tagline: "Double the luxury", description: "The Double Axle Hummer H2 offers extended luxury with its unique configuration. More space, more amenities, and more unforgettable moments.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Dancing Pole", "Extended Interior", "Climate Control"], images: getVehicleImages("hummer-h2-double-axle") },
  { slug: "hummer-h2-triple-axle", name: "Hummer H2 Triple Axle", type: "limo", passengers: 30, tagline: "The ultimate Hummer experience", description: "Our Triple Axle Hummer H2 is the most impressive limousine in our fleet. Accommodating up to 30 passengers, it provides unmatched luxury.", features: ["LED Lighting", "Premium Sound System", "Multiple Bar Areas", "Leather Seating", "Flat Screen TVs", "Dancing Poles", "VIP Section", "Full Laser Show"], images: getVehicleImages("hummer-h2-triple-axle") },
  { slug: "infiniti-qx56", name: "Infiniti QX56", type: "limo", passengers: 20, tagline: "Japanese precision, American luxury", description: "The Infiniti QX56 limousine blends sophisticated Japanese engineering with premium luxury features. A refined choice for up to 20 passengers.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TVs", "Fiber Optic Ceiling", "Climate Control", "Privacy Glass"], images: getVehicleImages("infiniti-qx56") },
  { slug: "lincoln-navigator", name: "Lincoln Navigator", type: "limo", passengers: 14, tagline: "Classic elegance personified", description: "The Lincoln Navigator limousine is the epitome of classic American elegance. Perfect for intimate gatherings of up to 14 guests.", features: ["LED Lighting", "Premium Sound System", "Bar Area", "Leather Seating", "Flat Screen TV", "Fiber Optic Ceiling", "Climate Control", "Red Carpet Service"], images: getVehicleImages("lincoln-navigator") },
];

// ===== SHUTTLE =====
export const shuttleBus: Vehicle = {
  slug: "shuttle-bus", name: "Shuttle Bus", type: "shuttle", passengers: 40, tagline: "Group transportation made easy", description: "Our Shuttle Bus is the perfect solution for large group transportation. Ideal for corporate events, weddings, and group outings.", features: ["Comfortable Seating", "Climate Control", "PA System", "Luggage Storage", "USB Charging", "Professional Driver"], images: getVehicleImages("shuttle-bus"),
};

export const allVehicles: Vehicle[] = [...partyBuses, ...limousines, shuttleBus];

// ===== SERVICES =====
export const services: Service[] = [
  { slug: "wedding", name: "Wedding Packages", shortDescription: "Make your special day unforgettable with our luxury wedding transportation.", description: "Your wedding day deserves nothing less than perfection. Avital Chicago Limousine offers premium wedding transportation packages that ensure you and your guests arrive in style. From the bride and groom's grand entrance to shuttling guests between venues, our fleet of luxury limousines and party buses provides the elegant backdrop your celebration deserves.", icon: "Heart" },
  { slug: "quinceanera", name: "Quinceañera", shortDescription: "Celebrate this milestone birthday with the grandeur it deserves.", description: "A quinceañera is a once-in-a-lifetime celebration, and the transportation should match the occasion's grandeur. Our stunning fleet features vibrant LED lighting, premium sound systems, and luxurious interiors that set the perfect tone for this milestone celebration.", icon: "Crown" },
  { slug: "night-parties", name: "Night Out Parties", shortDescription: "Turn your night out into an unforgettable experience on wheels.", description: "Why wait until you arrive at the club when the party can start the moment you step aboard? Our night-out party bus and limousine service transforms your evening into an unforgettable adventure with premium sound systems, LED lighting, bar areas, and dancing poles.", icon: "Music" },
  { slug: "prom", name: "Prom Night", shortDescription: "Arrive at prom in style with our premium limo service.", description: "Prom night is one of the most memorable events of your high school years, and arriving in a luxury limousine or party bus makes it truly special. Our vehicles are meticulously maintained and our chauffeurs are professional, courteous, and focused on safety.", icon: "GraduationCap" },
  { slug: "bachelor-bachelorette", name: "Bachelor & Bachelorette", shortDescription: "The ultimate pre-wedding celebration on wheels.", description: "Send the bride or groom off in style with our bachelor and bachelorette party transportation. Our party buses are the ultimate venue for pre-wedding celebrations, complete with dance floors, premium sound systems, LED lighting, and full bar setups.", icon: "PartyPopper" },
  { slug: "concerts-sports", name: "Concerts & Sports Events", shortDescription: "Skip the traffic and parking hassle — arrive like a VIP.", description: "Heading to a concert at the United Center, a Bears game at Soldier Field, or a Cubs game at Wrigley? Let us handle the transportation so you can focus on enjoying the event. Our party buses offer pre-game tailgating on wheels.", icon: "Trophy" },
  { slug: "birthday", name: "Birthday Celebrations", shortDescription: "Make your birthday the talk of the town with a luxury ride.", description: "Whether you're turning 21 or 50, a birthday celebration aboard one of our luxury party buses or limousines is an experience like no other. We offer custom decoration packages and can coordinate with venues for a seamless celebration.", icon: "Cake" },
  { slug: "graduation", name: "Graduation Celebrations", shortDescription: "Celebrate your academic achievement in grand style.", description: "You've worked hard to earn your degree — now it's time to celebrate in style. Our graduation transportation packages ensure you arrive at your ceremony and after-party in luxury.", icon: "Award" },
  { slug: "kids-party-bus", name: "Kids Party Bus", shortDescription: "Safe, fun, and unforgettable birthday parties for kids.", description: "Give your child a birthday party they'll never forget with our Kids Party Bus service. Our specially configured party buses provide a safe, fun, and exciting environment for children's celebrations with age-appropriate music and supervised fun.", icon: "Star" },
];

// ===== AREAS =====
export const areas: Area[] = [
  { slug: "aurora", name: "Aurora", description: "Premium party bus and limousine rental services in Aurora, IL. Serving the second-largest city in Illinois with luxury transportation for all occasions." },
  { slug: "naperville", name: "Naperville", description: "Luxury limousine and party bus services in Naperville, IL. From weddings to corporate events, we provide top-tier transportation." },
  { slug: "joliet", name: "Joliet", description: "Professional limo and party bus rental in Joliet, IL. Experience luxury transportation for your next event." },
  { slug: "elgin", name: "Elgin", description: "Avital Chicago provides premium party bus and limo services in Elgin, IL. Book your luxury ride today." },
  { slug: "waukegan", name: "Waukegan", description: "Luxury transportation services in Waukegan, IL. Party buses and limousines for every occasion." },
  { slug: "palatine", name: "Palatine", description: "Premium party bus and limousine rental in Palatine, IL. Professional chauffeurs and stunning vehicles." },
  { slug: "arlington-heights", name: "Arlington Heights", description: "Luxury party bus and limo services in Arlington Heights, IL. Making every journey unforgettable." },
  { slug: "schaumburg", name: "Schaumburg", description: "Professional limo and party bus rental in Schaumburg, IL. Premium transportation for all events." },
  { slug: "bloomington", name: "Bloomington", description: "Luxury transportation services in Bloomington, IL. Party buses and limousines available for all occasions." },
  { slug: "bolingbrook", name: "Bolingbrook", description: "Premium party bus and limo rental in Bolingbrook, IL. Experience the best in luxury transportation." },
  { slug: "cicero", name: "Cicero", description: "Luxury party bus and limousine services in Cicero, IL. Professional, reliable transportation." },
  { slug: "decatur", name: "Decatur", description: "Premium limo and party bus rental serving Decatur, IL. Book luxury transportation for your next event." },
  { slug: "des-plaines", name: "Des Plaines", description: "Luxury limousine and party bus services in Des Plaines, IL. Premium vehicles and professional chauffeurs." },
  { slug: "evanston", name: "Evanston", description: "Professional party bus and limo rental in Evanston, IL. Luxury transportation for every occasion." },
  { slug: "oak-lawn", name: "Oak Lawn", description: "Luxury party bus and limousine services in Oak Lawn, IL. From proms to weddings, we deliver." },
  { slug: "orland-park", name: "Orland Park", description: "Premium limo and party bus rental in Orland Park, IL. Experience true luxury transportation." },
  { slug: "rockford", name: "Rockford", description: "Luxury transportation services in Rockford, IL. Party buses and limousines for all events." },
  { slug: "skokie", name: "Skokie", description: "Professional party bus and limo services in Skokie, IL. Book your luxury ride today." },
  // Additional areas from old site
  { slug: "berwyn", name: "Berwyn", description: "Luxury party bus and limousine rental in Berwyn, IL. Premium transportation for all occasions." },
  { slug: "buffalo-grove", name: "Buffalo Grove", description: "Professional limo and party bus services in Buffalo Grove, IL." },
  { slug: "downers-grove", name: "Downers Grove", description: "Premium party bus and limousine rental in Downers Grove, IL." },
  { slug: "elmhurst", name: "Elmhurst", description: "Luxury transportation services in Elmhurst, IL. Party buses and limousines available." },
  { slug: "glenview", name: "Glenview", description: "Professional party bus and limo rental in Glenview, IL." },
  { slug: "hoffman-estates", name: "Hoffman Estates", description: "Luxury party bus and limousine services in Hoffman Estates, IL." },
  { slug: "lombard", name: "Lombard", description: "Premium limo and party bus rental in Lombard, IL." },
  { slug: "mount-prospect", name: "Mount Prospect", description: "Luxury limousine and party bus services in Mount Prospect, IL." },
  { slug: "normal", name: "Normal", description: "Professional party bus and limo rental serving Normal, IL." },
  { slug: "oak-park", name: "Oak Park", description: "Luxury transportation services in Oak Park, IL." },
  { slug: "plainfield", name: "Plainfield", description: "Premium party bus and limousine rental in Plainfield, IL." },
  { slug: "tinley-park", name: "Tinley Park", description: "Professional limo and party bus services in Tinley Park, IL." },
  { slug: "wheaton", name: "Wheaton", description: "Luxury party bus and limousine rental in Wheaton, IL." },
];
